name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ssh onto host, clone, and restart the service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          rm -rf ronnie-bot
          git clone https://github.com/Monkeyanator/ronnie-bot.git && cd ronnie-bot
          make build
          systemctl restart --user ronnie.service
